-- Enable RLS to prevent public access via Supabase REST API
ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS facebook_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS post_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS model_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS image_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS brand_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS custom_themes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS media_library ENABLE ROW LEVEL SECURITY;
